### ISSUE TITLE
兄弟，只有分享出来的百度网盘链接才能比较啊？

### ISSUE THREAD

**Issue by CharlesFulton** [zhangqi-ulua/BaiduPanCompareTools#1]
当分享出来的百度网盘链接，提示"此链接内容可能涉及侵权、色情、反动、低俗等信息，无法访问"，是否就无法使用该软件了呢？

我一个目录下共计一万多个小文件，通过BaiduPCSGO上传后，发现文件总数总是对不上。找到您这里的。

但是一万多个文件总有那么几十个是违规的，于是就无法分享整个目录。。。。。。

**Comment by zhangqi-ulua** [comment]
我没明白你的意思。我只见过这个分享整体被屏蔽访问了。看你的描述，分享的链接根目录没有被屏蔽，而是里面有部分文件夹被屏蔽？ 你加下我QQ具体说下吧  2246549866

**Comment by zhangqi-ulua** [comment]
软件初衷就是别人分享的并且持续更新，用这个工具方便比对变化。
自己网盘中的，没有分享出去的，请求的API都是不同的，故本软件并不支持
目前的情况，如果就那么十几个不行导致无法分享，最好就手工删除后分享处理后再用软件吧

**Comment by CharlesFulton** [comment]
哦了。感谢回复。

您的软件初衷看来跟我的需求不太一致。但是依旧是个很好的软件。感谢！
